name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Node.js dependencies
        run: npm install
      - name: Hexo Generate
        run: npm run build
      - name: Hexo Deploy
        run: |
          git config user.email "travis+bot@travismiller.com"
          git config user.name "Travis Miller (bot)"
          npm run deploy
